module.exports = class Data1783195404984 {
    name = 'Data1783195404984'

    async up(db) {
        await db.query(`CREATE TABLE "piece_token" ("id" character varying NOT NULL, "contract_address" text NOT NULL, "token_id" text NOT NULL, "serial" numeric NOT NULL, "owner" text NOT NULL, "minted_at" TIMESTAMP WITH TIME ZONE NOT NULL, "last_transfer_at" TIMESTAMP WITH TIME ZONE NOT NULL, "last_transfer_block" integer NOT NULL, "collection_id" character varying, CONSTRAINT "PK_cf1154eff1130321de03effcf14" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_piece_token_collection_4db847cc" ON "piece_token" ("collection_id") `)
        await db.query(`CREATE INDEX "idx_piece_token_contract_address_336969f5" ON "piece_token" ("contract_address") `)
        await db.query(`CREATE INDEX "idx_piece_token_serial_c87b1c3e" ON "piece_token" ("serial") `)
        await db.query(`CREATE INDEX "idx_piece_token_owner_253d152c" ON "piece_token" ("owner") `)
        await db.query(`CREATE INDEX "idx_piece_token_last_transfer_at_2eb0caf6" ON "piece_token" ("last_transfer_at") `)
        await db.query(`CREATE TABLE "piece_transfer" ("id" character varying NOT NULL, "contract_address" text NOT NULL, "token_id" text NOT NULL, "from" text NOT NULL, "to" text NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "block_number" integer NOT NULL, "log_index" integer NOT NULL, "hash" text NOT NULL, "collection_id" character varying, CONSTRAINT "PK_285c7036bf089eb3cc2b39680d5" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_piece_transfer_collection_58e26a18" ON "piece_transfer" ("collection_id") `)
        await db.query(`CREATE INDEX "idx_piece_transfer_contract_address_0dcd2e55" ON "piece_transfer" ("contract_address") `)
        await db.query(`CREATE INDEX "idx_piece_transfer_token_id_679f8bc4" ON "piece_transfer" ("token_id") `)
        await db.query(`CREATE INDEX "idx_piece_transfer_from_176b982e" ON "piece_transfer" ("from") `)
        await db.query(`CREATE INDEX "idx_piece_transfer_to_dcf3def6" ON "piece_transfer" ("to") `)
        await db.query(`CREATE INDEX "idx_piece_transfer_timestamp_8975d08e" ON "piece_transfer" ("timestamp") `)
        await db.query(`CREATE INDEX "idx_piece_transfer_block_number_76e63e97" ON "piece_transfer" ("block_number") `)
        await db.query(`CREATE INDEX "idx_piece_transfer_hash_9ddcfa89" ON "piece_transfer" ("hash") `)
        await db.query(`CREATE TABLE "piece_collection" ("id" character varying NOT NULL, "edition" text NOT NULL, "symbol" text NOT NULL, "first_seen_block" integer NOT NULL, "total_supply" integer NOT NULL, CONSTRAINT "PK_191627615f2443949db6e069a89" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_piece_collection_first_seen_block_be93318a" ON "piece_collection" ("first_seen_block") `)
        await db.query(`CREATE TABLE "ruby_transfer" ("id" character varying NOT NULL, "from" text NOT NULL, "to" text NOT NULL, "value" numeric NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "block_number" integer NOT NULL, "log_index" integer NOT NULL, "hash" text NOT NULL, CONSTRAINT "PK_dac9c1d503d1c5d13ca9d9303bf" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_ruby_transfer_from_1c95d546" ON "ruby_transfer" ("from") `)
        await db.query(`CREATE INDEX "idx_ruby_transfer_to_dcb8b618" ON "ruby_transfer" ("to") `)
        await db.query(`CREATE INDEX "idx_ruby_transfer_timestamp_18d85315" ON "ruby_transfer" ("timestamp") `)
        await db.query(`CREATE INDEX "idx_ruby_transfer_block_number_79876a55" ON "ruby_transfer" ("block_number") `)
        await db.query(`CREATE INDEX "idx_ruby_transfer_hash_62355050" ON "ruby_transfer" ("hash") `)
        await db.query(`ALTER TABLE "piece_token" ADD CONSTRAINT "FK_30c6ed880ea0e994fd846fb4227" FOREIGN KEY ("collection_id") REFERENCES "piece_collection"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "piece_transfer" ADD CONSTRAINT "FK_153036461f78c5c1c40906983e9" FOREIGN KEY ("collection_id") REFERENCES "piece_collection"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`ALTER TABLE "piece_transfer" DROP CONSTRAINT "FK_153036461f78c5c1c40906983e9"`)
        await db.query(`ALTER TABLE "piece_token" DROP CONSTRAINT "FK_30c6ed880ea0e994fd846fb4227"`)
        await db.query(`DROP INDEX "public"."idx_ruby_transfer_hash_62355050"`)
        await db.query(`DROP INDEX "public"."idx_ruby_transfer_block_number_79876a55"`)
        await db.query(`DROP INDEX "public"."idx_ruby_transfer_timestamp_18d85315"`)
        await db.query(`DROP INDEX "public"."idx_ruby_transfer_to_dcb8b618"`)
        await db.query(`DROP INDEX "public"."idx_ruby_transfer_from_1c95d546"`)
        await db.query(`DROP TABLE "ruby_transfer"`)
        await db.query(`DROP INDEX "public"."idx_piece_collection_first_seen_block_be93318a"`)
        await db.query(`DROP TABLE "piece_collection"`)
        await db.query(`DROP INDEX "public"."idx_piece_transfer_hash_9ddcfa89"`)
        await db.query(`DROP INDEX "public"."idx_piece_transfer_block_number_76e63e97"`)
        await db.query(`DROP INDEX "public"."idx_piece_transfer_timestamp_8975d08e"`)
        await db.query(`DROP INDEX "public"."idx_piece_transfer_to_dcf3def6"`)
        await db.query(`DROP INDEX "public"."idx_piece_transfer_from_176b982e"`)
        await db.query(`DROP INDEX "public"."idx_piece_transfer_token_id_679f8bc4"`)
        await db.query(`DROP INDEX "public"."idx_piece_transfer_contract_address_0dcd2e55"`)
        await db.query(`DROP INDEX "public"."idx_piece_transfer_collection_58e26a18"`)
        await db.query(`DROP TABLE "piece_transfer"`)
        await db.query(`DROP INDEX "public"."idx_piece_token_last_transfer_at_2eb0caf6"`)
        await db.query(`DROP INDEX "public"."idx_piece_token_owner_253d152c"`)
        await db.query(`DROP INDEX "public"."idx_piece_token_serial_c87b1c3e"`)
        await db.query(`DROP INDEX "public"."idx_piece_token_contract_address_336969f5"`)
        await db.query(`DROP INDEX "public"."idx_piece_token_collection_4db847cc"`)
        await db.query(`DROP TABLE "piece_token"`)
    }
}
